# Generated by Django 5.1.1 on 2024-09-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default=0, help_text='Генерируется при регистрации', max_length=6, verbose_name='Инвайт-код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который Вас пригласил', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Кем приглашён'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, help_text='Укажите номер телефона', max_length=32, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
